name: Build
on: push
jobs:
  Deploy: 
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm ci 
      - name: Lint appliation
        run: npm run lint
      - name: Build application
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: build
          name: build-files
 
  
       