name: Deploy
on: push
jobs:
  Lint: 
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm i 
      - name: Lint appliation
        run: npm run lint
  Build: 
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm i 
      - name: Build appliation
        run: npm run build
  
       