name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
 
  
env:
  SERVER_HOST: 158.160.35.130 
  SERVER_USER: fominykh
  SERVER_PATH: /home/fominykh/rating_front/build
jobs:
  deploy: 
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
     
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.3.1
        with:
          key: "${{ secrets.ONLY_SERVER_KEY }}"
          known_hosts: "just-a-placeholder-so-we-dont-get-errors"
      - name: Generate auth hosts
        run: ssh-keyscan -H ${{ env.SERVER_HOST }} >> ~/.ssh/known_hosts
      - name: Install dependecies
        run: npm ci 
      - name: Build application
        run: npm run build
      - name: Deploy
        run: scp -r ./build/* ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }}:${{ env.SERVER_PATH }}
      - name: Отправка сообщения в группу telegram
        uses: colutius/Telegram-Msg@main
        with:
          chatid: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          disable_notification: true
          message: |
            @${{ github.actor }} отправил: ${{ github.event.commits[0].message }}
          button: true
          button_name: Посмотреть изменения
          button_url: https://github.com/${{ github.repository }}/commit/${{github.sha}}
          is_notify: false
          is_preview: false

